name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services: 
      postgres: 
        image: postgres:alpine
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB:  ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-comd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

